# Generated by Django 4.1 on 2025-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
