# Generated by Django 4.1 on 2025-12-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_associado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='senha',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
    ]
